Parameters:
  VpcCidrBlock:
    Description: Please enter the IP range (CIDR notation) for this VPC
    Type: String
    Default: 10.0.0.0/16
  PublicSubnet1CidrBlock:
    Description: the public subnet
    Type: String
    Default: 10.0.1.0/24
  PrivateSubnet1CidrBlock:
    Description: the private subnet
    Type: String
    Default: 10.0.2.0/24


Resources:
  # No. 1
  VPC:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: !Ref VpcCidrBlock
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags: 
        - Key: Name 
          Value: 'Challenge2 vpc'
      
  # No. 2
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties: 
        Tags: 
          - Key: 'Name'
            Value: 'Challenge2 Internet gateway'
      
  # No. 3
  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties: 
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC

  # No. 4 - Public subnet
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
        VpcId: !Ref VPC
        CidrBlock: !Ref PublicSubnet1CidrBlock
        MapPublicIpOnLaunch: true
        Tags: 
            - Key: Name 
              Value: Challenge2 Public Subnet (AZ1)

  # # No. 4 - Private subnet
  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
        VpcId: !Ref VPC
        CidrBlock: !Ref PrivateSubnet1CidrBlock
        MapPublicIpOnLaunch: true
        Tags: 
            - Key: Name 
              Value: Challenge2 Private Subnet (AZ1)

 # No. 5
  NAT:
    Type: AWS::EC2::NatGateway
    Properties: 
        SubnetId: !Ref PublicSubnet1
        AllocationId: !GetAtt EIP.AllocationId
        Tags:
            - Key: Name 
              Value: Challenge2  NAT Gateway

  # No. 6
  EIP:
    Type: AWS::EC2::EIP
    DependsOn: InternetGatewayAttachment
    Properties: 
        Domain: VPC
        Tags: 
            - Key: Name 
              Value: Challenge2  ElasticIP

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties: 
        Tags: 
          - Key: Name
            Value: Public Route Table
        VpcId: !Ref VPC

  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties: 
        Tags: 
          - Key: "Name"
            Value: "Private Route Table"
        VpcId: !Ref VPC

  AssociatePUBRT:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet1

  AssociatePRIVRT:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      RouteTableId: !Ref PrivateRouteTable
      SubnetId: !Ref PrivateSubnet1

  PublicInternetRoute:
    Type: AWS::EC2::Route
    DependsOn: InternetGatewayAttachment
    Properties: 
        RouteTableId: !Ref PublicRouteTable
        DestinationCidrBlock: 0.0.0.0/0
        GatewayId: !Ref InternetGateway


  PrivateInternetOutboundRoute:
    Type: AWS::EC2::Route
    Properties: 
        RouteTableId: !Ref PrivateRouteTable
        DestinationCidrBlock: 0.0.0.0/0
        NatGatewayId: !Ref NAT


Outputs: 
    VPC:
        Description: A reference to the created VPC
        Value: !Ref VPC
        Export: 
          Name: Challenge2-VPC

    PublicSubnet:
        Description: A reference to the create Public Subnet
        Value: !Ref PublicSubnet1
        Export: 
          Name: Challenge2-PublicSubnet

    PrivateSubnet:
        Description: A reference to the create Private Subnet
        Value: !Ref PrivateSubnet1
        Export:
          Name: Challenge2-PrivateSubnet
